### ISSUE TITLE
関数名の prefix

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/hpc-mruby#10]
ユーザが定義、使用した関数名をなんでも許すと、 C 組み込みの関数名などとぶつかってしまうので、 `hpc_puts`、`hpc_fib` みたいに prefix をつけるのはどうでしょうか。

**Comment by nineties** [comment]
ユーザ定義関数が一つでもコンパイルされた側では型によって複数の実体が生じるのでprefixではなくてマングリングが必要です。型を付けてからの作業ですね。マングリングの規則はC++とほぼ同じです。
