### ISSUE TITLE
ビルドスクリプトへのhpcmrb/lib以下の規則追加

### ISSUE THREAD

**Issue by nineties** [tomykaira/hpc-mruby#12]
`hpcmrb/lib`以下のファイルをコンパイルしアーカイブにする。

**Comment by tomykaira** [comment]
意図がおなじかどうか分かりませんが、次の作業を生田さんか小川さんにおねがいします。
- 生成した .c ファイルをコンパイルする仕組み
- ライブラリ(libのなかにある .c ファイル)の関数をつかえる形でリンクする(やりかたは任せます。.o にしておいて gcc で本体をコンパイルするときに読むのが楽か)
- `compiled_main` を蹴る `main` の定義(for_fib の PR に私が手でかいたものがあるので、そんなかんじ)
- 以上をまとめてコンパイルできるようにするコマンドを表示 or 実行

`class_compile` というブランチで fib の生成ができる状態にしたので、ここからさらにブランチをきって作業してください。

**Comment by atetubou** [comment]
class_compileというブランチがpushされていないように見えます。
確認お願いします。

重ね重ねすいません。勘違いでした。

**Comment by atetubou** [comment]
すいません。間違ってcloseしました

**Comment by hi-ogawa** [comment]
とりあえずですがfibの実行ファイルをコマンドから作成できるようにMakefileを直接書き換えました。(Rakeの使い方がわからないのですいません)

一応手順を書いておきます。

$ make lib_builtin_driver
 gccでhpcmrb/lib以下の.cを.oにコンパイルし、arで.aとしてひとつのファイルにアーカイブします。

$ make compile_by_hpcmrb FILE=./benchmark/fib39
まずhpcmrbでFILE.rbをFILE.hpcmrb.cに変換。
次にgccでFILE.hpcmrb.cをmruby.h、builtin.hを取り込みながら単体でFILE.oにコンパイル。
その後に、builtin.cやdriver.cの実体があるlib_builtin_driver.aとlibmruby.aとFILE.oから実行ファイルを作成。

ところどころadhocな変更をしてますがとりあえずfibは動きます(puts関数をhpcmrb_putsに置き換えたり)

**Comment by hi-ogawa** [comment]
fib_executeとゆうbranchに上げました。
