### ISSUE TITLE
足りない組み込み関数の追加

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/hpc-mruby#21]
次の関数定義がたりていないので、 `builtin.c` に追加しておいてください。
mruby 本体で実験して、引数と返り値の型の関係が合うようにしましょう。
名前はこのとおりでおねがいします。

callee は限定的だと思われるので、それ以外の場合はエラーになるような実装でもいいです。

‘sqrt_1’
‘num_uminus_0’
‘to_i_0’
‘to_f_0’
‘chr_0’
‘rand_0’
‘cos_1’
‘sin_1’
‘to_s_0’

**Comment by tomykaira** [comment]
最新の class_compile からブランチを切ってください

**Comment by tomykaira** [comment]
rand_0 は module を実装すればいけるっぽいので、本当はここには入らないのですが、
module をやるのが面倒かもしれないので C の組み込みのでも呼んどいてもらえるとたすかります。

**Comment by tomykaira** [comment]
@atetubou @hi-ogawa

これ今日の午前中におねがいします。

**Comment by hi-ogawa** [comment]
class_compile3にあげました。
対応してる型などはコメントに書いてます。
エラー時は標準出力にエラーを吐いて、nilを返します。

**Comment by tomykaira** [comment]
あ、じぶんでやっちゃいました。
先に連絡すればよかったですね…ごめんなさい。

**Comment by tomykaira** [comment]
FYI ですが、 raise_error しても大丈夫みたいです。普通に異常終了します。
