### ISSUE TITLE
ao-render の benchmark

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/hpc-mruby#24]
プレゼン用に、複数の環境での実績がほしいのでデータ取りをおねがいします。

**Comment by atetubou** [comment]
学科PC上で、`class_compile`ブランチの`5194664ef52acc2de5a0fa655c8a9092a36d6032`までのコミットで測りました。

hpcmrb
real    9m5.949s
user    9m4.514s
sys     0m0.664s

mruby
real    7m28.547s
user    7m27.820s
sys     0m0.256s

hpcmrbのほうはMakefileに最適化オプションがついていないようなので、-gを-Ofastに変えた所

real    8m23.107s
user    8m21.935s
sys     0m0.668s

というような結果にかわりましたが、学科PCではmrubyよりも速いというような結果にはなりませんでした。

**Comment by tomykaira** [comment]
よくわからないんですが、 `print` のところにデバッグ用ファイル出力をいれたのが響いてるかもしれません。
ためしに外してみてください。

また、いまはデバッグ用に mruby 本体の -O3 をはずしているので、そっちをつけて全体を再コンパイルし、再度両方を走らせてみてください。
(tasks/toolchains/gcc.rake で指定しています)

何回かやると速くなるかもしれません。

いくらなんでも遅いはずはないんですが、私の環境でも一回、遅くなったことがあったので謎です。

**Comment by atetubou** [comment]
debug出力と-gを外し、すべて-O3オプションに変えてコンパイルしなおした所、

hpcmrb
real    3m25.270s
user    3m24.929s
sys     0m0.136s

mruby
real    3m11.482s
user    3m11.276s
sys     0m0.004s

という結果になりました。
速度はだいぶ向上してますが、2回やっても、どちらも時間は殆どかわりませんでした。

静的リンクによってインライン展開などグローバルな最適化があまり出来ないせいかもしれないと思い、builtin.cをリンクせずにao-render.hpcmrb.cの先頭に直接貼り付けたりもしましたが、

real  3m19.045s
user  3m18.652s
sys 0m0.184s

という結果に終わりました。

**Comment by tomykaira** [comment]
検証ありがとうございます。

手元でもう一度やってみたいので、いま修正してもらったものを別 branch にして上げてもらってもいいでしょうか？

**Comment by atetubou** [comment]
`ao-render_hpcmrb_c`というブランチにあげておきました。
make compile_modified_ao-render
として実行ファイルを生成してください。

**Comment by tomykaira** [comment]
かろうじて勝ちましたが。あんまかわらないっすね。

```
not modified
real    2m3.627s
user    2m2.636s
sys     0m0.604s

modified
real    2m2.977s
user    2m2.108s
sys     0m0.492s

mruby
real    2m16.631s
user    2m16.193s
sys     0m0.012s
```

最適化可能な箇所はいくつかみつけてあるので、明日の夜までがんばってください。
生田さんの腕の見せ所ですよ :sushi:

**Comment by tomykaira** [comment]
ここまで行きました。
再度テスト & できれば最適化おねがいします。

```
real    1m26.824s
user    1m26.545s
sys     0m0.004s
real 1:26.822s
```

module のバグ取りをしたので、出力が真に一致するようになりました。

**Comment by atetubou** [comment]
お疲れ様です。
学科PCで現状の`class_compile`をやったところ、以下のようにだいぶ早くなってました。(-gオプションあり)

real    3m9.127s
user    3m8.172s
sys 0m0.680s

すいませんが、最適化に関してはよさそうな方法があまり思いついていないので、期待しないでおいてください。

**Comment by tomykaira** [comment]
スライド用の他の言語（とくにgccとjavaとruby）でのベンチは取れてますか？

**Comment by atetubou** [comment]
benchmark用のブランチのresult.tsvにgcc,java,rubyの分はあります。

**Comment by tomykaira** [comment]
何度もすみませんが、クラスをぶっこわしてだいぶ早くなったと思うので、もう一度試してもらえますか？

@@ topaz に勝ちたかったんですが…

**Comment by atetubou** [comment]
学科PC上で-gなし-O3で以下のようになりました。

real    0m31.231s
user    0m30.806s
sys 0m0.384s
