### ISSUE TITLE
やればできそうな最適化

### ISSUE THREAD

**Issue by tomykaira** [tomykaira/hpc-mruby#25]
コードをながめて、最適化できそうな項目をあげてみました。
もし余裕があったらやってみてください。
- instance variable を最初に参照されたときに local variable にいれる。
  複数回参照される場合は高速化できる。一度しか参照されない場合もデメリットはない。
  iv_set するときには local のほうにもいれる。

``` c
mrb_value
Vec_vlength(mrb_value __self__)
{
    mrb_value x = mrb_iv_get(mrb, __self__, mrb_intern(mrb, "x"));
    mrb_value y = mrb_iv_get(mrb, __self__, mrb_intern(mrb, "y"));
    mrb_value z = mrb_iv_get(mrb, __self__, mrb_intern(mrb, "z"));
    return sqrt_1(1, Math, num_add_1(1, num_add_1(1, num_mul_1(1, x, x), num_mul_1(1, y, y)), num_mul_1(1, z, z)));
}
```
- setter を iv_set に展開する
  いまは setter の呼出が multiplexer -> 本体 -> iv_set となっていて無駄がおおい
  setter の中に副作用がないことは容易に確認できる(assignment しかない && assignment の lhs == @(関数名) && rhs == setter 引数)
  すべてのおなじ名前の関数の出現について setter であったら、call を iv_set でおきかえる
  本当は guard をいれなければならないが、mruby の範囲では、組み込み関数でおなじ名前のものがなければコンパイルタイムに確実に setter だと思う、ということもできる
  getter にかんしてもおなじことができる

ひろくいうと同じしくみで inlining もできる。たぶん現状の実装で gcc の inlining はあまり期待できないので。
- ひとつの式のなかでの算術演算をまとめる
  型推論が必要。組み込み関数の引数と返り値について型情報をあたえれば結構型がわかる。

``` ruby
occlusion = (ntheta.to_f * nphi.to_f - occlusion) / (ntheta.to_f * nphi.to_f)
```

occlusion がなんであれ、結果は float になるので、最初に occlusion を to_f して、あとは float 同士の計算としておこない、最後に代入するときに mrb_float_value にする。

``` c
occlusion = mrb_float_value(mrb_float(ntheta) * mrb_float(nphi) - mrb_float(occlusion)) / (mrb_float(ntheta) * mrb_float(nphi))
```

**Comment by tomykaira** [comment]
プロファイリングもせずに適当なこといってすいませんでした。

プロファイリングしたら内部処理で生成している mrb_intern が非常に時間とっていたので直しました。

次のボトルネックは mrb_iv_get と Vec_vdot なので、上でいっていることがおおむねあてはまります。
![2013-05-12-19-31-10](https://f.cloud.github.com/assets/789929/492799/19bb3828-baef-11e2-981e-e5c7a9d75ae4.png)

**Comment by atetubou** [comment]
iv_setの後に呼ばれている、iv_getをsetで使われた変数に置き換えることはできますか？

``` c
Vec_z_set(mrb_value __self__, mrb_value v)
{
    mrb_iv_set(mrb, __self__, __i_z, v);
    return mrb_iv_get(mrb, __self__, __i_z);
}
```

↓

``` c
Vec_z_set(mrb_value __self__, mrb_value v)
{
    mrb_iv_set(mrb, __self__, __i_z, v);
    return v;
}
```

**Comment by tomykaira** [comment]
その変更をしても意味が変わらないかということであれば、かわりません
